// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (id, user_id, name, token_hash, prefix, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, prefix, last_used_at, expires_at, created_at
`

type CreateApiTokenParams struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	Name      string        `json:"name"`
	TokenHash string        `json:"token_hash"`
	Prefix    string        `json:"prefix"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	CreatedAt int64         `json:"created_at"`
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createApiToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :execrows
DELETE FROM api_tokens WHERE id = ? AND user_id = ?
`

type DeleteApiTokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApiToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT id, user_id, name, token_hash, prefix, last_used_at, expires_at, created_at FROM api_tokens WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiTokensByUser = `-- name: ListApiTokensByUser :many
SELECT id, user_id, name, token_hash, prefix, last_used_at, expires_at, created_at FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListApiTokensByUser(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listApiTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiToken = `-- name: TouchApiToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchApiTokenParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         string        `json:"id"`
}

func (q *Queries) TouchApiToken(ctx context.Context, arg TouchApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchApiToken, arg.LastUsedAt, arg.ID)
	return err
}
