// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countExercises = `-- name: CountExercises :one
SELECT count(*) AS total FROM exercises
`

func (q *Queries) CountExercises(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExercises)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBuiltinExercise = `-- name: CreateBuiltinExercise :exec
INSERT INTO exercises (
    id, user_id, name, exercise_type, primary_muscle, secondary_muscles,
    equipment, instructions, is_archived, created_at, updated_at
) VALUES (?, NULL, ?, ?, ?, ?, ?, ?, 0, ?, ?)
`

type CreateBuiltinExerciseParams struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	ExerciseType     string `json:"exercise_type"`
	PrimaryMuscle    string `json:"primary_muscle"`
	SecondaryMuscles string `json:"secondary_muscles"`
	Equipment        string `json:"equipment"`
	Instructions     string `json:"instructions"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

func (q *Queries) CreateBuiltinExercise(ctx context.Context, arg CreateBuiltinExerciseParams) error {
	_, err := q.db.ExecContext(ctx, createBuiltinExercise,
		arg.ID,
		arg.Name,
		arg.ExerciseType,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Instructions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
    id, user_id, name, exercise_type, primary_muscle, secondary_muscles,
    equipment, instructions, is_archived, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq
`

type CreateExerciseParams struct {
	ID               string         `json:"id"`
	UserID           sql.NullString `json:"user_id"`
	Name             string         `json:"name"`
	ExerciseType     string         `json:"exercise_type"`
	PrimaryMuscle    string         `json:"primary_muscle"`
	SecondaryMuscles string         `json:"secondary_muscles"`
	Equipment        string         `json:"equipment"`
	Instructions     string         `json:"instructions"`
	IsArchived       int64          `json:"is_archived"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ExerciseType,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Instructions,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExerciseType,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Instructions,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq FROM exercises
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetExercise(ctx context.Context, id string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExerciseType,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Instructions,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq FROM exercises
WHERE (user_id = ? OR user_id IS NULL) AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context, userID sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ExerciseType,
			&i.PrimaryMuscle,
			&i.SecondaryMuscles,
			&i.Equipment,
			&i.Instructions,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExercise = `-- name: SoftDeleteExercise :execrows
UPDATE exercises
SET deleted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteExerciseParams struct {
	DeletedAt sql.NullInt64  `json:"deleted_at"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
}

func (q *Queries) SoftDeleteExercise(ctx context.Context, arg SoftDeleteExerciseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteExercise,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = ?, exercise_type = ?, primary_muscle = ?, secondary_muscles = ?,
    equipment = ?, instructions = ?, is_archived = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
RETURNING id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq
`

type UpdateExerciseParams struct {
	Name             string         `json:"name"`
	ExerciseType     string         `json:"exercise_type"`
	PrimaryMuscle    string         `json:"primary_muscle"`
	SecondaryMuscles string         `json:"secondary_muscles"`
	Equipment        string         `json:"equipment"`
	Instructions     string         `json:"instructions"`
	IsArchived       int64          `json:"is_archived"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
	UserID           sql.NullString `json:"user_id"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise,
		arg.Name,
		arg.ExerciseType,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Instructions,
		arg.IsArchived,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExerciseType,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Instructions,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
