// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Exercise struct {
	ID               string         `json:"id"`
	UserID           sql.NullString `json:"user_id"`
	Name             string         `json:"name"`
	ExerciseType     string         `json:"exercise_type"`
	PrimaryMuscle    string         `json:"primary_muscle"`
	SecondaryMuscles string         `json:"secondary_muscles"`
	Equipment        string         `json:"equipment"`
	Instructions     string         `json:"instructions"`
	IsArchived       int64          `json:"is_archived"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	DeletedAt        sql.NullInt64  `json:"deleted_at"`
}

type RefreshToken struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt int64         `json:"expires_at"`
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	CreatedAt int64         `json:"created_at"`
}

type Routine struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	FolderID   sql.NullString `json:"folder_id"`
	Title      string         `json:"title"`
	Notes      string         `json:"notes"`
	OrderIndex int64          `json:"order_index"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	DeletedAt  sql.NullInt64  `json:"deleted_at"`
}

type RoutineExercise struct {
	ID            string        `json:"id"`
	RoutineID     string        `json:"routine_id"`
	ExerciseID    string        `json:"exercise_id"`
	OrderIndex    int64         `json:"order_index"`
	Notes         string        `json:"notes"`
	RestSeconds   int64         `json:"rest_seconds"`
	SupersetGroup sql.NullInt64 `json:"superset_group"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
}

type RoutineFolder struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	OrderIndex int64         `json:"order_index"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
}

type RoutineSet struct {
	ID                string          `json:"id"`
	RoutineExerciseID string          `json:"routine_exercise_id"`
	OrderIndex        int64           `json:"order_index"`
	SetType           string          `json:"set_type"`
	TargetWeight      sql.NullFloat64 `json:"target_weight"`
	TargetReps        sql.NullInt64   `json:"target_reps"`
	TargetRpe         sql.NullFloat64 `json:"target_rpe"`
	TargetDuration    sql.NullInt64   `json:"target_duration"`
	CreatedAt         int64           `json:"created_at"`
	UpdatedAt         int64           `json:"updated_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Settings     string `json:"settings"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}
