// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type RefreshToken struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt int64         `json:"expires_at"`
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	CreatedAt int64         `json:"created_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Settings     string `json:"settings"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}
