// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Sync: changed-since reads (include soft-deleted for tombstones) + LWW upserts.
	// Reads use a per-user monotonic server_seq cursor (see migration 00009): pull is
	// `server_seq > cursor`, ordered by server_seq. server_seq itself is assigned by
	// triggers on every write (see the migration), so no write path can forget it.
	ChangedExercises(ctx context.Context, arg ChangedExercisesParams) ([]Exercise, error)
	ChangedRoutineFolders(ctx context.Context, arg ChangedRoutineFoldersParams) ([]RoutineFolder, error)
	ChangedRoutines(ctx context.Context, arg ChangedRoutinesParams) ([]Routine, error)
	ChangedWorkouts(ctx context.Context, arg ChangedWorkoutsParams) ([]Workout, error)
	ClearRoutinesFolder(ctx context.Context, arg ClearRoutinesFolderParams) error
	CountExerciseUsage(ctx context.Context, arg CountExerciseUsageParams) (int64, error)
	CountExercises(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error)
	CreateBuiltinExercise(ctx context.Context, arg CreateBuiltinExerciseParams) error
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error)
	CreateRoutineExercise(ctx context.Context, arg CreateRoutineExerciseParams) (RoutineExercise, error)
	CreateRoutineFolder(ctx context.Context, arg CreateRoutineFolderParams) (RoutineFolder, error)
	CreateRoutineSet(ctx context.Context, arg CreateRoutineSetParams) (RoutineSet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	CreateWorkoutExercise(ctx context.Context, arg CreateWorkoutExerciseParams) (WorkoutExercise, error)
	CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error)
	DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) (int64, error)
	DeleteRoutineExercisesByRoutine(ctx context.Context, routineID string) error
	DeleteWorkoutExercisesByWorkout(ctx context.Context, workoutID string) error
	GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetExercise(ctx context.Context, id string) (Exercise, error)
	GetExerciseForSync(ctx context.Context, id string) (Exercise, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoutine(ctx context.Context, id string) (Routine, error)
	GetRoutineFolder(ctx context.Context, id string) (RoutineFolder, error)
	GetRoutineFolderForSync(ctx context.Context, id string) (RoutineFolder, error)
	GetRoutineForSync(ctx context.Context, id string) (Routine, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWorkout(ctx context.Context, id string) (Workout, error)
	GetWorkoutForSync(ctx context.Context, id string) (Workout, error)
	ListApiTokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	ListExercises(ctx context.Context, userID sql.NullString) ([]Exercise, error)
	// Routine exercises + sets (children, replaced wholesale on update) ------------
	ListRoutineExercises(ctx context.Context, routineID string) ([]RoutineExercise, error)
	// Folders ---------------------------------------------------------------------
	ListRoutineFolders(ctx context.Context, userID string) ([]RoutineFolder, error)
	ListRoutineSetsForRoutine(ctx context.Context, routineID string) ([]RoutineSet, error)
	// Routines --------------------------------------------------------------------
	ListRoutines(ctx context.Context, userID string) ([]Routine, error)
	ListWorkoutExercises(ctx context.Context, workoutID string) ([]WorkoutExercise, error)
	ListWorkoutSetsForWorkout(ctx context.Context, workoutID string) ([]WorkoutSet, error)
	ListWorkouts(ctx context.Context, userID string) ([]Workout, error)
	RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) (int64, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error)
	SoftDeleteExercise(ctx context.Context, arg SoftDeleteExerciseParams) (int64, error)
	SoftDeleteRoutine(ctx context.Context, arg SoftDeleteRoutineParams) (int64, error)
	SoftDeleteRoutineFolder(ctx context.Context, arg SoftDeleteRoutineFolderParams) (int64, error)
	SoftDeleteWorkout(ctx context.Context, arg SoftDeleteWorkoutParams) (int64, error)
	TouchApiToken(ctx context.Context, arg TouchApiTokenParams) error
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error)
	UpdateRoutineFolder(ctx context.Context, arg UpdateRoutineFolderParams) (RoutineFolder, error)
	UpdateRoutineMeta(ctx context.Context, arg UpdateRoutineMetaParams) (Routine, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWorkoutMeta(ctx context.Context, arg UpdateWorkoutMetaParams) (Workout, error)
	UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error
	UpsertRoutine(ctx context.Context, arg UpsertRoutineParams) error
	UpsertRoutineFolder(ctx context.Context, arg UpsertRoutineFolderParams) error
	UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error
}

var _ Querier = (*Queries)(nil)
