// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (id, user_id, folder_id, title, notes, order_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at
`

type CreateRoutineParams struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	FolderID   sql.NullString `json:"folder_id"`
	Title      string         `json:"title"`
	Notes      string         `json:"notes"`
	OrderIndex int64          `json:"order_index"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRowContext(ctx, createRoutine,
		arg.ID,
		arg.UserID,
		arg.FolderID,
		arg.Title,
		arg.Notes,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Title,
		&i.Notes,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRoutineExercise = `-- name: CreateRoutineExercise :one
INSERT INTO routine_exercises (id, routine_id, exercise_id, order_index, notes, rest_seconds, superset_group, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, routine_id, exercise_id, order_index, notes, rest_seconds, superset_group, created_at, updated_at
`

type CreateRoutineExerciseParams struct {
	ID            string        `json:"id"`
	RoutineID     string        `json:"routine_id"`
	ExerciseID    string        `json:"exercise_id"`
	OrderIndex    int64         `json:"order_index"`
	Notes         string        `json:"notes"`
	RestSeconds   int64         `json:"rest_seconds"`
	SupersetGroup sql.NullInt64 `json:"superset_group"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
}

func (q *Queries) CreateRoutineExercise(ctx context.Context, arg CreateRoutineExerciseParams) (RoutineExercise, error) {
	row := q.db.QueryRowContext(ctx, createRoutineExercise,
		arg.ID,
		arg.RoutineID,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.Notes,
		arg.RestSeconds,
		arg.SupersetGroup,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoutineExercise
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.RestSeconds,
		&i.SupersetGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoutineFolder = `-- name: CreateRoutineFolder :one
INSERT INTO routine_folders (id, user_id, name, order_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, name, order_index, created_at, updated_at, deleted_at
`

type CreateRoutineFolderParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Name       string `json:"name"`
	OrderIndex int64  `json:"order_index"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateRoutineFolder(ctx context.Context, arg CreateRoutineFolderParams) (RoutineFolder, error) {
	row := q.db.QueryRowContext(ctx, createRoutineFolder,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoutineFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRoutineSet = `-- name: CreateRoutineSet :one
INSERT INTO routine_sets (id, routine_exercise_id, order_index, set_type, target_weight, target_reps, target_rpe, target_duration, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, routine_exercise_id, order_index, set_type, target_weight, target_reps, target_rpe, target_duration, created_at, updated_at
`

type CreateRoutineSetParams struct {
	ID                string          `json:"id"`
	RoutineExerciseID string          `json:"routine_exercise_id"`
	OrderIndex        int64           `json:"order_index"`
	SetType           string          `json:"set_type"`
	TargetWeight      sql.NullFloat64 `json:"target_weight"`
	TargetReps        sql.NullInt64   `json:"target_reps"`
	TargetRpe         sql.NullFloat64 `json:"target_rpe"`
	TargetDuration    sql.NullInt64   `json:"target_duration"`
	CreatedAt         int64           `json:"created_at"`
	UpdatedAt         int64           `json:"updated_at"`
}

func (q *Queries) CreateRoutineSet(ctx context.Context, arg CreateRoutineSetParams) (RoutineSet, error) {
	row := q.db.QueryRowContext(ctx, createRoutineSet,
		arg.ID,
		arg.RoutineExerciseID,
		arg.OrderIndex,
		arg.SetType,
		arg.TargetWeight,
		arg.TargetReps,
		arg.TargetRpe,
		arg.TargetDuration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoutineSet
	err := row.Scan(
		&i.ID,
		&i.RoutineExerciseID,
		&i.OrderIndex,
		&i.SetType,
		&i.TargetWeight,
		&i.TargetReps,
		&i.TargetRpe,
		&i.TargetDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoutineExercisesByRoutine = `-- name: DeleteRoutineExercisesByRoutine :exec
DELETE FROM routine_exercises WHERE routine_id = ?
`

func (q *Queries) DeleteRoutineExercisesByRoutine(ctx context.Context, routineID string) error {
	_, err := q.db.ExecContext(ctx, deleteRoutineExercisesByRoutine, routineID)
	return err
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at FROM routines WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRoutine(ctx context.Context, id string) (Routine, error) {
	row := q.db.QueryRowContext(ctx, getRoutine, id)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Title,
		&i.Notes,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoutineFolder = `-- name: GetRoutineFolder :one
SELECT id, user_id, name, order_index, created_at, updated_at, deleted_at FROM routine_folders WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRoutineFolder(ctx context.Context, id string) (RoutineFolder, error) {
	row := q.db.QueryRowContext(ctx, getRoutineFolder, id)
	var i RoutineFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRoutineExercises = `-- name: ListRoutineExercises :many

SELECT id, routine_id, exercise_id, order_index, notes, rest_seconds, superset_group, created_at, updated_at FROM routine_exercises WHERE routine_id = ? ORDER BY order_index
`

// Routine exercises + sets (children, replaced wholesale on update) ------------
func (q *Queries) ListRoutineExercises(ctx context.Context, routineID string) ([]RoutineExercise, error) {
	rows, err := q.db.QueryContext(ctx, listRoutineExercises, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineExercise{}
	for rows.Next() {
		var i RoutineExercise
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.Notes,
			&i.RestSeconds,
			&i.SupersetGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutineFolders = `-- name: ListRoutineFolders :many

SELECT id, user_id, name, order_index, created_at, updated_at, deleted_at FROM routine_folders WHERE user_id = ? AND deleted_at IS NULL ORDER BY order_index, name
`

// Folders ---------------------------------------------------------------------
func (q *Queries) ListRoutineFolders(ctx context.Context, userID string) ([]RoutineFolder, error) {
	rows, err := q.db.QueryContext(ctx, listRoutineFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineFolder{}
	for rows.Next() {
		var i RoutineFolder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutineSetsForRoutine = `-- name: ListRoutineSetsForRoutine :many
SELECT rs.id, rs.routine_exercise_id, rs.order_index, rs.set_type, rs.target_weight, rs.target_reps, rs.target_rpe, rs.target_duration, rs.created_at, rs.updated_at FROM routine_sets rs
JOIN routine_exercises re ON rs.routine_exercise_id = re.id
WHERE re.routine_id = ? ORDER BY rs.order_index
`

func (q *Queries) ListRoutineSetsForRoutine(ctx context.Context, routineID string) ([]RoutineSet, error) {
	rows, err := q.db.QueryContext(ctx, listRoutineSetsForRoutine, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineSet{}
	for rows.Next() {
		var i RoutineSet
		if err := rows.Scan(
			&i.ID,
			&i.RoutineExerciseID,
			&i.OrderIndex,
			&i.SetType,
			&i.TargetWeight,
			&i.TargetReps,
			&i.TargetRpe,
			&i.TargetDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutines = `-- name: ListRoutines :many

SELECT id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at FROM routines WHERE user_id = ? AND deleted_at IS NULL ORDER BY order_index, title
`

// Routines --------------------------------------------------------------------
func (q *Queries) ListRoutines(ctx context.Context, userID string) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Title,
			&i.Notes,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoutine = `-- name: SoftDeleteRoutine :execrows
UPDATE routines SET deleted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteRoutineParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
}

func (q *Queries) SoftDeleteRoutine(ctx context.Context, arg SoftDeleteRoutineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteRoutine,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteRoutineFolder = `-- name: SoftDeleteRoutineFolder :execrows
UPDATE routine_folders SET deleted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteRoutineFolderParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
}

func (q *Queries) SoftDeleteRoutineFolder(ctx context.Context, arg SoftDeleteRoutineFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteRoutineFolder,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRoutineFolder = `-- name: UpdateRoutineFolder :one
UPDATE routine_folders SET name = ?, order_index = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL RETURNING id, user_id, name, order_index, created_at, updated_at, deleted_at
`

type UpdateRoutineFolderParams struct {
	Name       string `json:"name"`
	OrderIndex int64  `json:"order_index"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) UpdateRoutineFolder(ctx context.Context, arg UpdateRoutineFolderParams) (RoutineFolder, error) {
	row := q.db.QueryRowContext(ctx, updateRoutineFolder,
		arg.Name,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i RoutineFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRoutineMeta = `-- name: UpdateRoutineMeta :one
UPDATE routines SET folder_id = ?, title = ?, notes = ?, order_index = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL RETURNING id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at
`

type UpdateRoutineMetaParams struct {
	FolderID   sql.NullString `json:"folder_id"`
	Title      string         `json:"title"`
	Notes      string         `json:"notes"`
	OrderIndex int64          `json:"order_index"`
	UpdatedAt  int64          `json:"updated_at"`
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) UpdateRoutineMeta(ctx context.Context, arg UpdateRoutineMetaParams) (Routine, error) {
	row := q.db.QueryRowContext(ctx, updateRoutineMeta,
		arg.FolderID,
		arg.Title,
		arg.Notes,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Title,
		&i.Notes,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
