// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlc

import (
	"context"
	"database/sql"
)

const changedExercises = `-- name: ChangedExercises :many

SELECT id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq FROM exercises WHERE user_id = ? AND server_seq > ? ORDER BY server_seq, id
`

type ChangedExercisesParams struct {
	UserID    sql.NullString `json:"user_id"`
	ServerSeq int64          `json:"server_seq"`
}

// Sync: changed-since reads (include soft-deleted for tombstones) + LWW upserts.
// Reads use a per-user monotonic server_seq cursor (see migration 00009): pull is
// `server_seq > cursor`, ordered by server_seq. server_seq itself is assigned by
// triggers on every write (see the migration), so no write path can forget it.
func (q *Queries) ChangedExercises(ctx context.Context, arg ChangedExercisesParams) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, changedExercises, arg.UserID, arg.ServerSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ExerciseType,
			&i.PrimaryMuscle,
			&i.SecondaryMuscles,
			&i.Equipment,
			&i.Instructions,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changedRoutineFolders = `-- name: ChangedRoutineFolders :many
SELECT id, user_id, name, order_index, created_at, updated_at, deleted_at, server_seq FROM routine_folders WHERE user_id = ? AND server_seq > ? ORDER BY server_seq, id
`

type ChangedRoutineFoldersParams struct {
	UserID    string `json:"user_id"`
	ServerSeq int64  `json:"server_seq"`
}

func (q *Queries) ChangedRoutineFolders(ctx context.Context, arg ChangedRoutineFoldersParams) ([]RoutineFolder, error) {
	rows, err := q.db.QueryContext(ctx, changedRoutineFolders, arg.UserID, arg.ServerSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineFolder{}
	for rows.Next() {
		var i RoutineFolder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changedRoutines = `-- name: ChangedRoutines :many
SELECT id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at, server_seq FROM routines WHERE user_id = ? AND server_seq > ? ORDER BY server_seq, id
`

type ChangedRoutinesParams struct {
	UserID    string `json:"user_id"`
	ServerSeq int64  `json:"server_seq"`
}

func (q *Queries) ChangedRoutines(ctx context.Context, arg ChangedRoutinesParams) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, changedRoutines, arg.UserID, arg.ServerSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Title,
			&i.Notes,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changedWorkouts = `-- name: ChangedWorkouts :many
SELECT id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at, server_seq FROM workouts WHERE user_id = ? AND server_seq > ? ORDER BY server_seq, id
`

type ChangedWorkoutsParams struct {
	UserID    string `json:"user_id"`
	ServerSeq int64  `json:"server_seq"`
}

func (q *Queries) ChangedWorkouts(ctx context.Context, arg ChangedWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, changedWorkouts, arg.UserID, arg.ServerSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoutineID,
			&i.Title,
			&i.Notes,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseForSync = `-- name: GetExerciseForSync :one
SELECT id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at, server_seq FROM exercises WHERE id = ? LIMIT 1
`

func (q *Queries) GetExerciseForSync(ctx context.Context, id string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseForSync, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExerciseType,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Instructions,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getRoutineFolderForSync = `-- name: GetRoutineFolderForSync :one
SELECT id, user_id, name, order_index, created_at, updated_at, deleted_at, server_seq FROM routine_folders WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoutineFolderForSync(ctx context.Context, id string) (RoutineFolder, error) {
	row := q.db.QueryRowContext(ctx, getRoutineFolderForSync, id)
	var i RoutineFolder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getRoutineForSync = `-- name: GetRoutineForSync :one
SELECT id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at, server_seq FROM routines WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoutineForSync(ctx context.Context, id string) (Routine, error) {
	row := q.db.QueryRowContext(ctx, getRoutineForSync, id)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Title,
		&i.Notes,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getWorkoutForSync = `-- name: GetWorkoutForSync :one
SELECT id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at, server_seq FROM workouts WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkoutForSync(ctx context.Context, id string) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutForSync, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const upsertExercise = `-- name: UpsertExercise :exec
INSERT INTO exercises (id, user_id, name, exercise_type, primary_muscle, secondary_muscles, equipment, instructions, is_archived, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name, exercise_type = excluded.exercise_type, primary_muscle = excluded.primary_muscle,
    secondary_muscles = excluded.secondary_muscles, equipment = excluded.equipment, instructions = excluded.instructions,
    is_archived = excluded.is_archived, updated_at = excluded.updated_at, deleted_at = excluded.deleted_at
WHERE excluded.updated_at >= exercises.updated_at
`

type UpsertExerciseParams struct {
	ID               string         `json:"id"`
	UserID           sql.NullString `json:"user_id"`
	Name             string         `json:"name"`
	ExerciseType     string         `json:"exercise_type"`
	PrimaryMuscle    string         `json:"primary_muscle"`
	SecondaryMuscles string         `json:"secondary_muscles"`
	Equipment        string         `json:"equipment"`
	Instructions     string         `json:"instructions"`
	IsArchived       int64          `json:"is_archived"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	DeletedAt        sql.NullInt64  `json:"deleted_at"`
}

func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error {
	_, err := q.db.ExecContext(ctx, upsertExercise,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ExerciseType,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Instructions,
		arg.IsArchived,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertRoutine = `-- name: UpsertRoutine :exec
INSERT INTO routines (id, user_id, folder_id, title, notes, order_index, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    folder_id = excluded.folder_id, title = excluded.title, notes = excluded.notes,
    order_index = excluded.order_index, updated_at = excluded.updated_at, deleted_at = excluded.deleted_at
WHERE excluded.updated_at >= routines.updated_at
`

type UpsertRoutineParams struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	FolderID   sql.NullString `json:"folder_id"`
	Title      string         `json:"title"`
	Notes      string         `json:"notes"`
	OrderIndex int64          `json:"order_index"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	DeletedAt  sql.NullInt64  `json:"deleted_at"`
}

func (q *Queries) UpsertRoutine(ctx context.Context, arg UpsertRoutineParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoutine,
		arg.ID,
		arg.UserID,
		arg.FolderID,
		arg.Title,
		arg.Notes,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertRoutineFolder = `-- name: UpsertRoutineFolder :exec
INSERT INTO routine_folders (id, user_id, name, order_index, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name, order_index = excluded.order_index, updated_at = excluded.updated_at, deleted_at = excluded.deleted_at
WHERE excluded.updated_at >= routine_folders.updated_at
`

type UpsertRoutineFolderParams struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	OrderIndex int64         `json:"order_index"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
}

func (q *Queries) UpsertRoutineFolder(ctx context.Context, arg UpsertRoutineFolderParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoutineFolder,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    routine_id = excluded.routine_id, title = excluded.title, notes = excluded.notes,
    start_time = excluded.start_time, end_time = excluded.end_time, updated_at = excluded.updated_at, deleted_at = excluded.deleted_at
WHERE excluded.updated_at >= workouts.updated_at
`

type UpsertWorkoutParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	RoutineID sql.NullString `json:"routine_id"`
	Title     string         `json:"title"`
	Notes     string         `json:"notes"`
	StartTime int64          `json:"start_time"`
	EndTime   sql.NullInt64  `json:"end_time"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
	DeletedAt sql.NullInt64  `json:"deleted_at"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkout,
		arg.ID,
		arg.UserID,
		arg.RoutineID,
		arg.Title,
		arg.Notes,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
