// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at
`

type CreateWorkoutParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	RoutineID sql.NullString `json:"routine_id"`
	Title     string         `json:"title"`
	Notes     string         `json:"notes"`
	StartTime int64          `json:"start_time"`
	EndTime   sql.NullInt64  `json:"end_time"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.ID,
		arg.UserID,
		arg.RoutineID,
		arg.Title,
		arg.Notes,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkoutExercise = `-- name: CreateWorkoutExercise :one
INSERT INTO workout_exercises (id, workout_id, exercise_id, order_index, notes, superset_group, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, workout_id, exercise_id, order_index, notes, superset_group, created_at, updated_at
`

type CreateWorkoutExerciseParams struct {
	ID            string        `json:"id"`
	WorkoutID     string        `json:"workout_id"`
	ExerciseID    string        `json:"exercise_id"`
	OrderIndex    int64         `json:"order_index"`
	Notes         string        `json:"notes"`
	SupersetGroup sql.NullInt64 `json:"superset_group"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
}

func (q *Queries) CreateWorkoutExercise(ctx context.Context, arg CreateWorkoutExerciseParams) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutExercise,
		arg.ID,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.Notes,
		arg.SupersetGroup,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.SupersetGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutSet = `-- name: CreateWorkoutSet :one
INSERT INTO workout_sets (id, workout_exercise_id, order_index, set_type, weight, reps, rpe, duration, distance, is_completed, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, workout_exercise_id, order_index, set_type, weight, reps, rpe, duration, distance, is_completed, created_at, updated_at
`

type CreateWorkoutSetParams struct {
	ID                string          `json:"id"`
	WorkoutExerciseID string          `json:"workout_exercise_id"`
	OrderIndex        int64           `json:"order_index"`
	SetType           string          `json:"set_type"`
	Weight            sql.NullFloat64 `json:"weight"`
	Reps              sql.NullInt64   `json:"reps"`
	Rpe               sql.NullFloat64 `json:"rpe"`
	Duration          sql.NullInt64   `json:"duration"`
	Distance          sql.NullFloat64 `json:"distance"`
	IsCompleted       int64           `json:"is_completed"`
	CreatedAt         int64           `json:"created_at"`
	UpdatedAt         int64           `json:"updated_at"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutSet,
		arg.ID,
		arg.WorkoutExerciseID,
		arg.OrderIndex,
		arg.SetType,
		arg.Weight,
		arg.Reps,
		arg.Rpe,
		arg.Duration,
		arg.Distance,
		arg.IsCompleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExerciseID,
		&i.OrderIndex,
		&i.SetType,
		&i.Weight,
		&i.Reps,
		&i.Rpe,
		&i.Duration,
		&i.Distance,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutExercisesByWorkout = `-- name: DeleteWorkoutExercisesByWorkout :exec
DELETE FROM workout_exercises WHERE workout_id = ?
`

func (q *Queries) DeleteWorkoutExercisesByWorkout(ctx context.Context, workoutID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutExercisesByWorkout, workoutID)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at FROM workouts WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetWorkout(ctx context.Context, id string) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkout, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkoutExercises = `-- name: ListWorkoutExercises :many
SELECT id, workout_id, exercise_id, order_index, notes, superset_group, created_at, updated_at FROM workout_exercises WHERE workout_id = ? ORDER BY order_index
`

func (q *Queries) ListWorkoutExercises(ctx context.Context, workoutID string) ([]WorkoutExercise, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutExercises, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutExercise{}
	for rows.Next() {
		var i WorkoutExercise
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.Notes,
			&i.SupersetGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSetsForWorkout = `-- name: ListWorkoutSetsForWorkout :many
SELECT ws.id, ws.workout_exercise_id, ws.order_index, ws.set_type, ws.weight, ws.reps, ws.rpe, ws.duration, ws.distance, ws.is_completed, ws.created_at, ws.updated_at FROM workout_sets ws
JOIN workout_exercises we ON ws.workout_exercise_id = we.id
WHERE we.workout_id = ? ORDER BY ws.order_index
`

func (q *Queries) ListWorkoutSetsForWorkout(ctx context.Context, workoutID string) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutSetsForWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutExerciseID,
			&i.OrderIndex,
			&i.SetType,
			&i.Weight,
			&i.Reps,
			&i.Rpe,
			&i.Duration,
			&i.Distance,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at FROM workouts WHERE user_id = ? AND deleted_at IS NULL ORDER BY start_time DESC
`

func (q *Queries) ListWorkouts(ctx context.Context, userID string) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoutineID,
			&i.Title,
			&i.Notes,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkout = `-- name: SoftDeleteWorkout :execrows
UPDATE workouts SET deleted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteWorkoutParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
}

func (q *Queries) SoftDeleteWorkout(ctx context.Context, arg SoftDeleteWorkoutParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteWorkout,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkoutMeta = `-- name: UpdateWorkoutMeta :one
UPDATE workouts SET routine_id = ?, title = ?, notes = ?, start_time = ?, end_time = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL RETURNING id, user_id, routine_id, title, notes, start_time, end_time, created_at, updated_at, deleted_at
`

type UpdateWorkoutMetaParams struct {
	RoutineID sql.NullString `json:"routine_id"`
	Title     string         `json:"title"`
	Notes     string         `json:"notes"`
	StartTime int64          `json:"start_time"`
	EndTime   sql.NullInt64  `json:"end_time"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
}

func (q *Queries) UpdateWorkoutMeta(ctx context.Context, arg UpdateWorkoutMetaParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutMeta,
		arg.RoutineID,
		arg.Title,
		arg.Notes,
		arg.StartTime,
		arg.EndTime,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Title,
		&i.Notes,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
